### ISSUE TITLE
Mobile devices bug

### ISSUE THREAD

**Issue by Themesfa** [exodusanto/lv-ripple#1]
In my theme each button has a ripple effect
but on the mobile device click action not working . means i click on button for do action and ripple effect showing but my action not running . in desktop version its working .
i remove the ripple and my problem solved .
i think this plugin has a bug in the mobile devices . please check .
thank ...

**Comment by exodusanto** [comment]
Hi @themesfa, i found this solution with pointer-events, for old browsers i use polyfill, i added it in the dependencies.

Let me know if it works for you too :)

**Comment by Themesfa** [comment]
no its not working for me. 
i use inspect element in chrome and in device toolbar i check my theme in 768*478 .
this problem not just for older browsers.

**Comment by Themesfa** [comment]
![gif](https://cloud.githubusercontent.com/assets/20536674/18740291/dc7c5a2e-80b5-11e6-9bd9-dd83cd4f746f.gif)

**Comment by exodusanto** [comment]
Try to set 
`rippleConfig.mobileTouch = true`

**Comment by Themesfa** [comment]
this solution working if i set mobileTouch false . so ripple not running and my action work well.
 i want to work together ripple and my action.
What should I do ?

**Comment by Themesfa** [comment]
this problem solved with update plugin .
now the new problem is ripple effect remove div class and add custom class => ripple-cont
why ??!!

**Comment by Themesfa** [comment]
you add this code in new version : 
cloneElement[0].className = "";
I remove this line and all thing works well ....

**Comment by exodusanto** [comment]
Yes, this is the commit: df92834

I had to recreate all markup because there was some problem with link element.

Now i'm pushing new stuff, update it and try it, if it doesn't work i will remove `cloneElement[0].className = "";`

**Comment by exodusanto** [comment]
Ok, i try it and i fix it.

Update to this commit: ee4328b

Let me know if it works.

**Comment by Themesfa** [comment]
yes . fixed .
thank you ...

**Comment by exodusanto** [comment]
You're welcome!
